#ifndef MYENUM_H
#define MYENUM_H

namespace OBJID		{ enum ID { BACKGROUND, BUTTON, DECORATION, MONSTER, PROJECTILE, TURRET, UI, UNIT, END }; }
namespace DATAID	{ enum ID { BACKGROUND, ANIMATION, BUTTON, DECORATION, ENGINE, MONSTER, STAGE, TURRET, UI, UNIT, END }; }

#endif // !MYENUM_H
